package com.jss.model;

import java.io.Serializable;
import java.util.Date;

public class Advisory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advisory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advisory.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advisory.cstid
     *
     * @mbg.generated
     */
    private Integer cstid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advisory.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advisory.fabudate
     *
     * @mbg.generated
     */
    private Date fabudate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advisory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advisory.id
     *
     * @return the value of advisory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advisory.id
     *
     * @param id the value for advisory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advisory.content
     *
     * @return the value of advisory.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advisory.content
     *
     * @param content the value for advisory.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advisory.cstid
     *
     * @return the value of advisory.cstid
     *
     * @mbg.generated
     */
    public Integer getCstid() {
        return cstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advisory.cstid
     *
     * @param cstid the value for advisory.cstid
     *
     * @mbg.generated
     */
    public void setCstid(Integer cstid) {
        this.cstid = cstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advisory.status
     *
     * @return the value of advisory.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advisory.status
     *
     * @param status the value for advisory.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advisory.fabudate
     *
     * @return the value of advisory.fabudate
     *
     * @mbg.generated
     */
    public Date getFabudate() {
        return fabudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advisory.fabudate
     *
     * @param fabudate the value for advisory.fabudate
     *
     * @mbg.generated
     */
    public void setFabudate(Date fabudate) {
        this.fabudate = fabudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Advisory other = (Advisory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getCstid() == null ? other.getCstid() == null : this.getCstid().equals(other.getCstid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getFabudate() == null ? other.getFabudate() == null : this.getFabudate().equals(other.getFabudate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getCstid() == null) ? 0 : getCstid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getFabudate() == null) ? 0 : getFabudate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", cstid=").append(cstid);
        sb.append(", status=").append(status);
        sb.append(", fabudate=").append(fabudate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}