package com.jss.mapper;

import com.jss.model.Advisory;

public interface AdvisoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    int insert(Advisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    int insertSelective(Advisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    Advisory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Advisory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advisory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Advisory record);
}